# Generated by Django 5.0.7 on 2025-11-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaspace_app', '0002_category_cart_order_address_plane_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='planes/'),
        ),
    ]
