# Generated by Django 5.0.7 on 2025-11-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaspace_app', '0003_plane_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bank Transfer', help_text='Payment method name', max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Optional instructions to display at checkout', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Display this payment method on checkout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Payment',
                'verbose_name_plural': 'Bank Payments',
            },
        ),
    ]
