# Generated by Django 5.0.7 on 2025-11-03 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaspace_app', '0004_bankpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='teaspace_app.order')),
                ('plane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaspace_app.plane')),
            ],
        ),
    ]
