# Generated by Django 5.0.7 on 2025-11-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaspace_app', '0005_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='rating',
        ),
    ]
