"""
Django settings for teaspace_p project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static
from django.urls import reverse_lazy
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()

environ.Env.read_env(os.path.join(BASE_DIR,'file.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-06r&&pa_y$oj!7-%jhf77!rgmo@jopwoe0m%oz9w%dx-g6$i&+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = ["taesaerospace.com"]
CSRF_TRUSTED_ORIGINS = ["https://taesaerospace.com"]


# taesaerospace.com


# Application definition
AUTH_USER_MODEL = 'teaspace_app.CustomUser'


INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'teaspace_app',
    'anymail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'teaspace_p.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'core/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'teaspace_p.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),  
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
# -----------------------
# Static & Media Settings
# -----------------------

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

if os.environ.get('ON_RAILWAY') == 'true':
    # -------------------
    # 🌍 PRODUCTION MODE
    # -------------------
    DEBUG = False

    # Static files collected here by collectstatic
    STATIC_ROOT = '/app/staticfiles'

    # Your app’s uploaded files
    MEDIA_ROOT = '/app/core/media'

else:
    # -------------------
    # 💻 LOCAL DEVELOPMENT
    # -------------------
    DEBUG = True

    # These are your working directories during development
    STATICFILES_DIRS = [
        BASE_DIR / 'core/static',
    ]
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    MEDIA_ROOT = BASE_DIR / 'core/media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ADMIN_EMAIL="info@taesaerospace.com"
EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
DEFAULT_FROM_EMAIL = "info@taesaerospace.com" 

RESEND_API_KEY = os.getenv("RESEND_API_KEY")

if not RESEND_API_KEY:
    print("❌ RESEND_API_KEY not found in environment!")
else:
    print("✅ RESEND_API_KEY loaded successfully")



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'






UNFOLD = {
    # ---- Branding ----
    "SITE_HEADER": "TAE Aerospace Admin",
    "SITE_TITLE": "TAE Aerospace Admin Panel",
    "SITE_SUBHEADER": "Manage planes, users, orders, and carts efficiently.",
    "SITE_URL": "/",  # link logo back to homepage

    # ---- Logo / Icons (light & dark mode support) ----
    "SITE_ICON": {
        "light": lambda request: static("assets/images/resources/logo-2.png"),
        "dark": lambda request: static("assets/images/resources/logo-2.png"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("assets/images/resources/logo-2.png"),
        "dark": lambda request: static("assets/images/resources/logo-2.png"),
    },

    # ---- Dashboard ----
    "DASHBOARD": {
        "show_search": True,
        "show_all_applications": False,
        "cards": [
            {
                "title": _("Users"),
                "icon": "group",
                "link": reverse_lazy("admin:teaspace_app_customuser_changelist"),
                "description": _("Manage all registered users."),
            },
            {
                "title": _("Categories"),
                "icon": "category",
                "link": reverse_lazy("admin:teaspace_app_category_changelist"),
                "description": _("Create and manage plane categories."),
            },
            {
                "title": _("Planes"),
                "icon": "airplanemode_active",
                "link": reverse_lazy("admin:teaspace_app_plane_changelist"),
                "description": _("Add, edit, or delete planes."),
            },
            {
                "title": _("Carts"),
                "icon": "shopping_cart",
                "link": reverse_lazy("admin:teaspace_app_cart_changelist"),
                "description": _("View user carts and items."),
            },
            {
                "title": _("Orders"),
                "icon": "assignment",
                "link": reverse_lazy("admin:teaspace_app_order_changelist"),
                "description": _("Track and manage user orders."),
            },
            {
                "title": _("Addresses"),
                "icon": "home",
                "link": reverse_lazy("admin:teaspace_app_address_changelist"),
                "description": _("View billing and shipping addresses."),
            },
        ],
    },

    # ---- Sidebar ----
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("User Management"),
                "icon": "group",
                "collapsible": False,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:teaspace_app_customuser_changelist"),
                    },
                ],
            },
            {
                "title": _("Plane Management"),
                "icon": "airplanemode_active",
                "collapsible": True,
                "items": [
                    {
                        "title": _("Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:teaspace_app_category_changelist"),
                    },
                    {
                        "title": _("Planes"),
                        "icon": "airplanemode_active",
                        "link": reverse_lazy("admin:teaspace_app_plane_changelist"),
                    },
                ],
            },
            {
                "title": _("Commerce"),
                "icon": "shopping_cart",
                "collapsible": True,
                "items": [
                    {
                        "title": _("Carts"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:teaspace_app_cart_changelist"),
                    },
                    {
                        "title": _("Orders"),
                        "icon": "assignment",
                        "link": reverse_lazy("admin:teaspace_app_order_changelist"),
                    },
                    {
                        "title": _("Addresses"),
                        "icon": "home",
                        "link": reverse_lazy("admin:teaspace_app_address_changelist"),
                    },
                     {
                        "title": _("Bank Payments"),
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:teaspace_app_bankpayment_changelist"),
                    },
                ],
            },
        ],
    },
}

